### ISSUE TITLE
ThemeProvider

### ISSUE THREAD

**Issue by rpelorosso** [airbnb/react-with-styles#126]
Hi! I'm reading [http://airbnb.io/projects/react-with-styles/](http://airbnb.io/projects/react-with-styles/) which mentions a ThemeProvider component that allows to change the theme used. 

I've noticed that I don't see it mentioned in the [Github repository readme](https://github.com/airbnb/react-with-styles) and that it doesn't seem to work with react-with-styles 2.3.1. 

Was it deprecated? If so, how can I change the selected theme, and register a theme with a name?

Thank you!

**Comment by rpelorosso** [comment]
Thank you @ljharb ! That's a shame :(

**Comment by ljharb** [comment]
Could you elaborate a bit on your use case?
