### ISSUE TITLE
Use performance.mark() and performance.measure() in development

### ISSUE THREAD

**Issue by lencioni** [airbnb/react-with-styles#140]
It would be nice to have more insight into how react-with-styles is performing in real world applications. We can use `performance.mark()` and `performance.measure()` to annotate the user timing pane in Chrome's performance devtool.

**Comment by ljharb** [comment]
We could maybe surround them in an env var so they get compiled out by default? We'll also have to make sure to always surround them in `if (typeof performance !== 'undefined')` since this code tends to run on the server too.

**Comment by lencioni** [comment]
Yes, absolutely. This should be contained in conditionals like:

```js
if (process.env.NODE_ENV !== 'production') {
  ...
}
```
