### ISSUE TITLE
Doesn't work with className?

### ISSUE THREAD

**Issue by towry** [airbnb/react-with-styles#163]
How to add custom className?

```jsx
<h3 { ...css(styles.title)} className="heading">title</h3>
```
h3 will only have one class name.

**Comment by ljharb** [comment]
You don't; all styling comes through `css`.

**Comment by MarcAlx** [comment]
Here's a "dirty" workaround to your problem :

`<h3 { ...css(styles.title)} className="heading">title</h3>`

Would be

`<h3  className={css(styles.title).className+" heading"}>title</h3>`
