### ISSUE TITLE
How does withStyles become aware of ThemedStyleSheet?

### ISSUE THREAD

**Issue by jaredpalmer** [airbnb/react-with-styles#19]
I made a ThemedStyleSheet.js and registered a default theme (exactly like the docs example), but I am getting errors that say that my component theme.default is undefined. Am I supposed to export ThemedStylesheet.js and import it somewhere? I am confused how context is getting set without somehow wrapping my app with ThemeProvider?

**Comment by lencioni** [comment]
Great question! Here's how we are currently doing this.

We have a file that registers the default theme and interface, and export all of the things you need from there. Then in your components you'll import things like `withStyles` and `css` from this file. To ensure maximum compatibility with the [eslint plugin](https://github.com/airbnb/eslint-plugin-react-with-styles), this file should probably be named `withStyles.js` (at least for now). This file could look something like:

```js
import aphroditeInterface from 'react-with-styles-interface-aphrodite';
import ThemedStyleSheet from 'react-with-styles/lib/ThemedStyleSheet';
import { css, withStyles } from 'react-with-styles';

import MyDefaultTheme from './MyDefaultTheme';

ThemedStyleSheet.registerDefaultTheme(MyDefaultTheme);
ThemedStyleSheet.registerInterface(aphroditeInterface);

export { css, withStyles, ThemedStyleSheet };
```

You could probably also avoid the importing and re-exporting if you wanted, as long as you have this initialization code running before you try to use `withStyles` (e.g. by adding it to the beginning of your bundle).

Does this help at all?

**Comment by jaredpalmer** [comment]
Yes! Thanks! This worked perfectly. Point of confusion was the [example which imports directly from `react-with-styles`](https://github.com/airbnb/react-with-styles/blob/master/README.md#how-to-use).

**Comment by lencioni** [comment]
Ah yes. I'll try to clarify that a little.

**Comment by lencioni** [comment]
@jaredpalmer I've pushed #21 to clarify this. I'd love your feedback on this change. Thanks!
