### ISSUE TITLE
.git included in npm distribution in version 3.2.2

### ISSUE THREAD

**Issue by conorhastings** [airbnb/react-with-styles#216]
causing failure on npm prune with error `Appears to be a git repo or submodule.`

Was failing build in CI and had to revert to previous version directly (was depended on with ^ by a direct dep while this was was a transitive dep)

confirmed by executing:
1. `npm pack react-with-styles`
2. `tar -xzf react-with-styles-3.2.2.tgz`
3. `cd ./package`
4. `ls -a`

**Comment by lencioni** [comment]
Thanks for the report! I'll try to fix this asap.

**Comment by conorhastings** [comment]
thanks! appreciate the quick reply

**Comment by lencioni** [comment]
I think this is a bug affecting some versions of npm (https://github.com/npm/npm/issues/20213). I've published 3.2.3 which should have this fixed now.

**Comment by conorhastings** [comment]
fixed!, thanks for the super quick work @lencioni
