### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by ranaryongpintu** [airbnb/react-with-styles#237]
Hi, please help to resolve this issues.

This is stack trace i get and it changes every time based on how we import module.
I am using material Ui in react. version 16.8.0

if i remove this file import  **__Sub__Admin_**. .then i works fine . 
if i keep this and run then it gives this error log..

Uncaught TypeError: Super expression must either be null or a function
    at index.browser.js:1195
    at index.browser.js:1194
    at Module.<anonymous> (index.browser.js:1186)
    at n (index.browser.js:15)
    at Object.e.exports (index.browser.js:327)
    at n (index.browser.js:15)
    at e.exports (index.browser.js:51)
    at Object.180 (index.browser.js:5)
    at f (__Sub__Admin__:1)
    **at Module.5730 (__Sub__Admin_.js:508)**

**Comment by ljharb** [comment]
This is unrelated to react-with-styles; it's likely due to trying to babel-transpile classes while extending a native `class`.
