### ISSUE TITLE
DateRangePickerInput: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by HakanSungur** [airbnb/react-with-styles#257]
Hello,
I'm trying to do React SSR with Express and I'm getting this error. DateRangePickerInput: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

**Comment by ljharb** [comment]
We don’t support react > 16 yet, and this error only occurs in React 18.
