### ISSUE TITLE
Not working with React Native

### ISSUE THREAD

**Issue by pozdena** [airbnb/react-with-styles#30]
Thanks for react-with-styles! It's working well with Aphrodite so far, but I can't get it to work in an existing or new React Native (0.33) project. The first problem I run into is having to install babel-preset-airbnb due to this error:

`TransformError: /Users/lespozdena/Desktop/AwesomeProject/node_modules/react-with-styles-interface-react-native/lib/reactNativeInterface.js: Couldn't find preset "airbnb" relative to directory "/Users/lespozdena/Desktop/AwesomeProject/node_modules/react-with-styles-interface-react-native"`

Clearing that dep lets the app run, but then react-with-styles does not ever deliver the styles prop (either via the default one or a custom-named one). The prop is always undefined. I never had this issue with React/Aphrodite.

**Comment by ljharb** [comment]
This is likely due to the RN packager (wrongly) attempting to transpile `node_modules`.

**Comment by lelandrichardson** [comment]
@pozdena what we do (with great sadness) is run the following command as an npm `postinstall` script:

```
(find node_modules -type f -name .babelrc | grep -v /react-native/ | xargs rm) || true
```

**Comment by pozdena** [comment]
@lelandrichardson Thanks, that avoids the transform error and having to install the preset, but styles still don't actually come through.

**Comment by jimmyhmiller** [comment]
@ljharb Is this something you consider an upstream problem? If so, has there been a bug filed? If not, any ideas for a solution?

**Comment by ljharb** [comment]
@jimmyhmiller yes, it's an upstream problem. The RN team is certainly aware that encouraging people to publish untranspiled code is problematic, but haven't yet made any moves to change that.

**Comment by pozdena** [comment]
Revisiting this, the workaround @lelandrichardson originally suggested now works! Unfortunately, I'm not sure what changed on our end.
