### ISSUE TITLE
confusion about modules

### ISSUE THREAD

**Issue by fsjoyti** [airbnb/react-with-styles#31]
Hi I would like to use react-with-styles for one of my project but I am confused on what it means by modules is it supposed to be a css file ? When I tried to do this in a CSS file my compiler shows me errors
<img width="183" alt="airbnbreactstyles" src="https://cloud.githubusercontent.com/assets/10965471/19417919/71541094-937e-11e6-9cfc-037396064041.PNG">

**Comment by lencioni** [comment]
Hi @fsjoyti! Thanks for your interest. This is not meant to be used in CSS files. Rather, it is a project to help you write CSS in JavaScript. Here's a more complete example, all contained in the same JSX file:

```jsx
function Foo({ styles }) {
  return (
    <div {...css(styles.foo)}>
      Foo
    </div>
  );
}

export default withStyles(() => {
  foo: {
    color: 'red',
  },
})(Foo);
```

I hope this helps!
