### ISSUE TITLE
.babelrc should be removed from npm

### ISSUE THREAD

**Issue by RanzQ** [airbnb/react-with-styles#44]
React Native packager doesn't find preset `airbnb`. Removing `.babelrc` fixes it.

https://github.com/gaearon/redux-thunk/issues/43

https://github.com/facebook/react-native/issues/4062

Also applies to [react-with-styles-interface-react-native](https://github.com/airbnb/react-with-styles-interface-react-native).

**Comment by ljharb** [comment]
No, it absolutely should not be - `npm explore foo && npm install && npm test` should always work. The RNP has a flaw in that it transpiles node_modules, and the proper place for a workaround is a postinstall script in your top-level app that removes all `.babelrc` files from your `node_modules`.

**Comment by RanzQ** [comment]
Ok, thanks for the tip. Thought `.babelrc` is unnecessary for transpiled npm package. :)

**Comment by ljharb** [comment]
No worries - untranspiled npm packages shouldn't exist; it's a flaw in the RN ecosystem that it's encouraged and allowed.

**Comment by RanzQ** [comment]
I also had the impression that untranspiled code would perform better if it's natively supported but that's [not true](https://www.redfin.com/blog/2016/04/es6-in-node-v6.html). So I get your point that all packages should be transpiled and there shouldn't be a need for RN packager to touch node_modules.

**Comment by ljharb** [comment]
Definitely not true - older syntax is almost always faster than newer syntax, because older syntax has had time to be optimized.
