### ISSUE TITLE
Module not found: 'aphrodite'

### ISSUE THREAD

**Issue by jorendemaeyer1996** [airbnb/react-with-styles#56]
I installed and followed everything thats in the docs and i've gotten this error.
 
![screen shot 2017-04-04 at 10 33 26](https://cloud.githubusercontent.com/assets/16215602/24648017/6fca7e00-1922-11e7-845c-b910d57b87d7.png)
![screen shot 2017-04-04 at 10 31 45](https://cloud.githubusercontent.com/assets/16215602/24648016/6fc912f4-1922-11e7-9986-9baebf9791a5.png)
<img width="1233" alt="screen shot 2017-04-04 at 10 24 25" src="https://cloud.githubusercontent.com/assets/16215602/24648018/6fcdcce0-1922-11e7-9a52-c180fce05366.png">

**Comment by ljharb** [comment]
Aphrodite is a peer dep of react-with-styles-interface-aphrodite; you have to manually add that to your toplevel package.json.

An `npm ls` will also reveal the missing dependency.
