### ISSUE TITLE
react-with-styles is now causing a React warning

### ISSUE THREAD

**Issue by callumlocke** [airbnb/react-with-styles#62]
I'm getting this warning when I use react-with-styles with the latest version of React:

![image](https://cloud.githubusercontent.com/assets/250617/24874158/8d796d46-1e1b-11e7-9b3b-043a009a63cd.png)

Is there any way to fix or suppress this?

**Comment by callumlocke** [comment]
hopefully fixed by linked PR

**Comment by lencioni** [comment]
I think this was fixed by v1.4.0. Please re-open if you are still having problems! Thanks!
