### ISSUE TITLE
Pass through styles?

### ISSUE THREAD

**Issue by merlinpatt** [airbnb/react-with-styles#94]
How do you recommend passing additional styling through to the underlying component?

For example, I have this Row component

```
const Row = ({children, styles}) => {
  return (
    <div {...css(styles.row)}>
      {children}
    </div>
  );
};
```

But I want to be able to change its style based on what other component I'm using it in, like so

```
<Row style={{backgroundColor: 'green'}}>...</Row>
<Row style={{color: 'blue'}}>...</Row>
```

I could just add the `style` prop and pass it through to the div, but that seems like it goes against the point of this library.

Can this new style somehow be passed through into the styles of the withStyles function so it generates a css class? Or do you have a different suggested best practice for doing this?

**Comment by ljharb** [comment]
It should have its own explicit prop. In other words, a component's parent shouldn't be able to style it directly - that's only its own responsibility.

**Comment by lencioni** [comment]
Thanks for asking this question!

As @ljharb said, adding explicit props to support the specific styling you need is the way to go. Here's an article that was written about CSS classes, but the same concepts apply in this case: https://brigade.engineering/don-t-pass-css-classes-between-components-e9f7ab192785

I hope that helps!
